CREATE DATABASE IF NOT EXISTS sculpture_museum
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE sculpture_museum;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE heykeltarashlar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(255) NOT NULL UNIQUE,
  dogum_ili VARCHAR(20) DEFAULT NULL,
  olum_ili VARCHAR(20) DEFAULT NULL,
  olke VARCHAR(100) DEFAULT NULL,
  foto VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE heykeltarash_metn (
  id INT AUTO_INCREMENT PRIMARY KEY,
  heykeltarash_id INT NOT NULL,
  lang CHAR(2) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  ad VARCHAR(255) NOT NULL,
  bio TEXT,
  meta_title VARCHAR(255) DEFAULT NULL,
  meta_desc VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_ht_lang (heykeltarash_id, lang),
  UNIQUE KEY uq_ht_slug (lang, slug),
  CONSTRAINT fk_ht_heykeltarash FOREIGN KEY (heykeltarash_id)
    REFERENCES heykeltarashlar(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE heykeller (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(255) NOT NULL UNIQUE,
  heykeltarash_id INT DEFAULT NULL,
  seher VARCHAR(100) DEFAULT NULL,
  il VARCHAR(50) DEFAULT NULL,
  material VARCHAR(100) DEFAULT NULL,
  olcu VARCHAR(100) DEFAULT NULL,
  lat DECIMAL(10,7) DEFAULT NULL,
  lng DECIMAL(10,7) DEFAULT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_h_heykeltarash FOREIGN KEY (heykeltarash_id)
    REFERENCES heykeltarashlar(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE heykel_metn (
  id INT AUTO_INCREMENT PRIMARY KEY,
  heykel_id INT NOT NULL,
  lang CHAR(2) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  ad VARCHAR(255) NOT NULL,
  lead TEXT,
  tarixi MEDIUMTEXT,
  tesviri MEDIUMTEXT,
  menasi MEDIUMTEXT,
  meta_title VARCHAR(255) DEFAULT NULL,
  meta_desc VARCHAR(255) DEFAULT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY uq_hm_lang (heykel_id, lang),
  UNIQUE KEY uq_hm_slug (lang, slug),
  CONSTRAINT fk_hm_heykel FOREIGN KEY (heykel_id)
    REFERENCES heykeller(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE fotolar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  heykel_id INT NOT NULL,
  fayl VARCHAR(255) NOT NULL,
  alt_metn VARCHAR(255) DEFAULT NULL,
  sira INT NOT NULL DEFAULT 0,
  esas TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_f_heykel FOREIGN KEY (heykel_id)
    REFERENCES heykeller(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE istinadlar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  heykel_id INT NOT NULL,
  lang CHAR(2) NOT NULL,
  metn VARCHAR(500) NOT NULL,
  url VARCHAR(500) DEFAULT NULL,
  sira INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_i_heykel FOREIGN KEY (heykel_id)
    REFERENCES heykeller(id) ON DELETE CASCADE
) ENGINE=InnoDB;